### ISSUE TITLE
How to avoid loops when traversing the graph?

### ISSUE THREAD

**Issue by qbengt** [rsc/pdf#5]
Greetings,

Given a PDF file that has a loop (ex: pages found from "Kids" have entries for "Parent" pointing back), how to I traverse the graph without getting stuck?

I tried saving the Values that I have visited, but they are not == to the new Values.

**Comment by rsc** [comment]
I don't believe there's a good way to do this, other than hard-coding a list of back-edges not to follow (starting with "Parent"). My guess is that the PDF format does not have too many back-edges that you have to exclude.
