### ISSUE TITLE
The Page.Content().S don't have any space character

### ISSUE THREAD

**Issue by ledongthuc** [rsc/pdf#7]
From code of https://github.com/rsc/pdf/blob/master/page.go#L421

I see you skip all ` ` character, why do you do it. Not sure I got your idea but when reading all text form pdf, we can't use the content and the result's very useless.

<img width="1425" alt="screen shot 2017-03-12 at 10 30 55 am" src="https://cloud.githubusercontent.com/assets/1828895/23828771/050f3c4c-070f-11e7-9a66-5453fb2952e9.png">

**Comment by puddingfactory** [comment]
Thank you for pointing this out!

After commenting out the `if` on Line 421 out and then adding one additional space when Y changes from one character to the next in my loop over pages & text, I was able to get basically what I was shooting for all along: text [cleanly] extracted from PDF.

So I'm curious as well: why exclude spaces?

I don't imagine it was a mistake and would speculate that spaces weren't the goal of the package... but... having spaces is supremely helpful when trying to work at the "word" level.

At the very least, I'm going to fork this repo now and would also be happy to submit a pull request with these changes in the near future. Only problem is that this fundamentally changes the output of the package and I'm not sure if this is something people would be happy about (but I sure would be).

**Comment by ledongthuc** [comment]
Thanks @puddingfactory, I'm very hapy with your library 👍
